### ISSUE TITLE
`error: ReferenceError: window is not defined` after updating to 1.1.0

### ISSUE THREAD

**Issue by cesarmiquel** [TimDumol/unix-crypt-td-js#4]
Hi! I'm running a Node application which uses this library and started getting this error. Upon further investigation I noticed this library had updated from 1.0.0 -> 1.1.0. This is the full stack trace. Any ideas what might be going on? 

```
Thu, 24 Oct 2019 15:34:13 GMT apicommon:apirequest Request  [GET] http://cache-back-development-varnish:80/api/backend/pagina12/navigation
error: ReferenceError: window is not defined
   at Object.<anonymous> (/usr/src/app/node_modules/unix-crypt-td-js/unix-crypt-td.min.js:1:63)
   at Module._compile (module.js:577:32)
   at Object.Module._extensions..js (module.js:586:10)
   at Module.load (module.js:494:32)
   at tryModuleLoad (module.js:453:12)
   at Function.Module._load (module.js:445:3)
   at Function.wrappedLoad [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:372:38)
   at Module.require (module.js:504:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/usr/src/app/node_modules/apache-crypt/src/index.js:4:13)
   at Module._compile (module.js:577:32)
   at Object.Module._extensions..js (module.js:586:10)
   at Module.load (module.js:494:32)
   at tryModuleLoad (module.js:453:12)
   at Function.Module._load (module.js:445:3)
   at Function.wrappedLoad [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:372:38)
   at Module.require (module.js:504:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/usr/src/app/node_modules/http-auth/src/auth/basic.js:13:15)
   at Module._compile (module.js:577:32)
   at Object.Module._extensions..js (module.js:586:10)
   at Module.load (module.js:494:32)
```

**Comment by TimDumol** [comment]
It's probably because of `'use strict';` preventing usage of the `window` global in Node apps. Let me see if I can fix it.

**Comment by TimDumol** [comment]
@cesarmiquel I just released 1.1.1 that should hopefully fix your issue. Please tell me if it's working now!

**Comment by TimDumol** [comment]
My bad. I just checked how `apache-crypt` uses my library and 1.1.4 should be the proper fix. At least, their tests pass now.

**Comment by christianviller** [comment]
I was having the same issue with another node application. Updated to 1.1.4 and it works now. Thanks Tim!

**Comment by cesarmiquel** [comment]
Hey @TimDumol ! Yes! Its working now for us. Thanks a million!! You can close this issue :-)

**Comment by cesarmiquel** [comment]
Closing. This works with the new version. Thanks again @TimDumol
